[package]
name = "raytracer"
version = "0.1.0"
authors = ["jecaspa <jean.caspar67610@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
image = "0.23.0"
threadpool = "1.7.1"